include:
  - path: ../waste-organisation-backend/compose.yml

services:
  cdp-defra-id-stub:
    image: defradigital/cdp-defra-id-stub:latest
    ports:
      - '3200:3200'
      - '3000:3000'
      - '7337:7337'
    depends_on:
      redis:
        condition: service_started
    environment:
      PORT: 3200
      NODE_ENV: development
      REDIS_HOST: redis
      SESSION_CACHE_ENGINE: redis
      USE_SINGLE_INSTANCE_CACHE: true
      APP_BASE_URL: http://localhost:3200
    networks:
      - cdp-tenant

  cdp-uploader:
    image: defradigital/cdp-uploader:latest
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      VIRTUAL_HOST: ~^uploader\..*\.sslip\.io
      VIRTUAL_PATH: /
      VIRTUAL_PORT: 7337
      PORT: 7337
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
      MOCK_VIRUS_SCAN_ENABLED: true
      MOCK_VIRUS_RESULT_DELAY: 3
      SQS_ENDPOINT: http://localstack:4566
      S3_ENDPOINT: http://localstack:4566
    network_mode: 'service:cdp-defra-id-stub'

  waste-organisation-frontend:
    build:
      context: .
      target: development
    volumes:
      - ./package.json:/home/node/package.json:z
      - ./package-lock.json:/home/node/package-lock.json:z
      - ./src:/home/node/src:z
      - ./webpack.config.js:/home/node/webpack.config.js:z
      - ./postcss.config.js:/home/node/postcss.config.js:z
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
      cdp-defra-id-stub:
        condition: service_started
      waste-organisation-backend:
        condition: service_started
      cdp-uploader:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      USE_SINGLE_INSTANCE_CACHE: true
      SESSION_CACHE_ENGINE: redis
      AUTH_DEFRA_ID_OIDC_CONFIGURATION_URL: 'http://localhost:3200/cdp-defra-id-stub/.well-known/openid-configuration'
      BACKEND_API: http://waste-organisation-backend:3001
      FILE_UPLOAD_SERVICE_URL: http://localhost:7337
      BACKEND_API_PRESHARED_KEY: test
      FEATURE_FLAG_UPDATE_SPREADSHEET: true
    network_mode: 'service:cdp-defra-id-stub'
